# Programación para *Data Science*

Unidad 4: Librerías científicas en Python
------------------------------------------------------

Esta Unidad se compone de 4 módulos: Matplotlib, Numpy, pandas y SciPy. A continuación, os proponemos una serie de ejercicios a realizar para cada uno de estos módulos.

# Ejercicios para practicar

**Los siguientes 4 ejercicios** no puntuan para la PEC, pero os recomendamos que los intentéis resolver antes de pasar a los ejercicios propios de la PEC. También podéis encontrar las soluciones a estos ejercicios al final del Notebook.


### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [6]:
import numpy as np

matriz = np.array([[1, 0], [2, -1]])

norma = np.linalg.norm(matriz)
determ = np.linalg.det(matriz)

print("La matriz es la siguiente:", matriz)
print("La norma de la matriz es: ", norma)
print("El determinante de la matriz es:", determ)

La matriz es la siguiente: [[ 1  0]
 [ 2 -1]]
La norma de la matriz es:  2.449489742783178
El determinante de la matriz es: -1.0


### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [7]:
i = np.arange(0., 1.1, 0.1)

arc = np.arcsin(i)
arcco = np.arccos(i)

print(arc)
print(arcco)

[0.         0.10016742 0.20135792 0.30469265 0.41151685 0.52359878
 0.64350111 0.7753975  0.92729522 1.11976951 1.57079633]
[1.57079633 1.47062891 1.36943841 1.26610367 1.15927948 1.04719755
 0.92729522 0.79539883 0.64350111 0.45102681 0.        ]


### Ejercicio 4
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [11]:
from random import randint

random = [randint(0, 9) for i in range(100)]

media = np.mean(random)
desv_std = np.std(random)

maximo = np.max(random)
minimo = np.min(random)

suma = np.sum(random)

uniq = np.unique(random)

print("Lista de valores enteros aleatorios:", random)
print("El valor medio es {}, y la desviación estándar es {}", (media, desv_std))
print("El valor máximo es {} y el mínimo {}", (maximo, minimo))
print("La suma de los valores de la lista es: ", suma)
print("Los valores únicos son: ", uniq)

Lista de valores enteros aleatorios: [5, 4, 7, 7, 8, 8, 5, 4, 3, 0, 8, 6, 8, 3, 9, 8, 6, 6, 5, 9, 2, 2, 3, 3, 9, 1, 7, 3, 7, 0, 7, 2, 0, 5, 6, 7, 3, 2, 2, 4, 8, 9, 9, 1, 6, 8, 6, 7, 7, 0, 6, 0, 0, 3, 5, 3, 4, 4, 1, 2, 1, 9, 3, 4, 4, 6, 8, 4, 9, 2, 1, 8, 7, 5, 9, 3, 6, 7, 7, 6, 1, 8, 5, 8, 4, 2, 5, 2, 2, 9, 3, 6, 7, 2, 4, 9, 9, 6, 4, 4]
El valor medio es {}, y la desviación estándar es {} (4.92, 2.711752201068527)
El valor máximo es {} y el mínimo {} (9, 0)
La suma de los valores de la lista es:  492
Los valores únicos son:  [0 1 2 3 4 5 6 7 8 9]


# Ejercicios para la actividad 4a

A continuación encontraréis los ejercicios que debéis completar en esta actividad y que
forman parte de la evaluación de esta unidad: Pandas y NumPy

## NumPy - Ejercicios

### Ejercicio 1
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort). **(0.5 puntos)**

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [12]:
m = np.array([[5,1,7],
              [0,7,4],
              [7,23,1]])


### Ejercicio 2
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`. **(0.5 puntos)**

In [14]:
def matrices(A,B):
    detA = A[0][0]*A[1][1]-A[0][1]*A[1][0]
    detB = B[0][0]*B[1][1]-B[0][1]*B[1][0]
    resultado = abs(detA*detB)
    print(resultado)
x = np.array([[5,1,7],
              [0,7,4]])
y = np.array([[4,4,67],
              [3,7,1]])
matrices(x,y)

560


### Ejercicio 3
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales **(0.5 puntos)**

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [17]:
a1 = np.array([(1,0,0,0,0,0,0,0,0,0),
               (0,1,0,0,0,0,0,0,0,0),
               (0,0,1,0,0,0,0,0,0,0),
               (0,0,0,1,0,0,0,0,0,0),
               (0,0,0,0,1,0,0,0,0,0),
               (0,0,0,0,0,1,0,0,0,0),
               (0,0,0,0,0,0,1,0,0,0),
               (0,0,0,0,0,0,0,1,0,0),
               (0,0,0,0,0,0,0,0,1,0),
               (0,0,0,0,0,0,0,0,0,1)])
a2 = np.eye(10)
np.array_equal(a1,a2)

True

### Ejercicio 4
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar. **(0.5 puntos)**

In [23]:
matriz = np.zeros(2*6).reshape(2,6)
 
for i in range(2):
    for j in range(6):
        if i%2 == 0:
            matriz[i][j] = i**2 + j
        else:
            matriz[i][j] = i-j**2
 
print(matriz)

[[  0.   1.   2.   3.   4.   5.]
 [  1.   0.  -3.  -8. -15. -24.]]


### Ejercicio 5
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué. **(0.5 puntos)**

In [32]:
A = np.random.random((5,5))
B = np.random.random((5,5))
mult = np.multiply(A,B)
mult2 = A*B
#print(A,B)
#print(mult)
#print(mult2)
C = np.random.random((4,5))
print(C)
D = np.random.random((5,5))
mult1 = np.multiply(C,D) # Este caso da error porque las dimensiones no son compatibles
mult3 = C*D

[[0.99226323 0.95760122 0.20463902 0.86888326]
 [0.50336051 0.41161189 0.95110359 0.97519964]
 [0.65983736 0.08896239 0.69027417 0.57703083]
 [0.57538627 0.18503982 0.14716103 0.70285673]
 [0.66720494 0.59162862 0.86597606 0.77500681]]


ValueError: operands could not be broadcast together with shapes (5,4) (5,5) 

## pandas - Ejercicios

### Ejercicio 1

Cargad los datos del fichero _got.csv_ en un _dataframe_. Este conjunto de datos recoge información de la [Guerra de los Cinco Reyes](https://awoiaf.westeros.org/index.php/War_of_the_Five_Kings) de las novelas de [Cancion de Hielo y Fuego](https://es.wikipedia.org/wiki/Canci%C3%B3n_de_hielo_y_fuego) de George R.R Martin.

Mostrad el número de filas del _dataframe_ y las etiquetas de los ejes. **(0.5 puntos)**

### Ejercicio 2

Agrupad los datos cargados en el ejercicio 1 por el principal bando atacante (*attacker\_1*). Para cada posición, mostrad el número de batallas y el resultado de la batalla (el resultado se encuentra en el campo *attacker\_outcome*). **(0.5 puntos)**

In [ ]:
# Respuesta

### Ejercicio 3

Mostrad los datos de las batallas donde el numero de participantes supera los 15000 "hombres" (contando ambos bandos: *attacker\_size* y *defender\_size*), el resultado haya sido favorable para el atacante, y la batalla se haya producido en invierno (_summer=0_).
 **(1 punto)**

In [ ]:
# Respuesta

### Ejercicio 4

Contad el número de lugares que aparecen más de una vez en _dataframe_ (campo _location_), utilizando las funciones de la librería _pandas_. ¿Existe algún lugar donde se haya realizado más de una batalla? Comprobad qué bandos estaban implicados. **(0.5 puntos)**

In [ ]:
# Respuesta

### Ejercicio 5

Añadid una nueva columna al _dataframe_ con un valor booleano indicando una predicción básica de si en una cierta batalla el bando atacante será vencedor. Definiremos el valor como _True_ sí el bando atacante es mayor al defensor, y como _False_ en caso contrario. Definid como _NaN_ aquellos casos en los que no haya número de tropas en ningún bando. ¿En que casos, identificados por el número de batalla (*battle\_number*), nuestra predicción coincide con el resultado real? **(1 punto)**

In [ ]:
# Respuesta

# Soluciones a los ejercicios para practicar

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [5]:
import numpy as np

# Creamos la matriz como un array bidimensional
m = np.array([[1, 0], [2, -1]])

# Y calculamos la normal y el determinante utilizando el módulo linalg
norm = np.linalg.norm(m)
det = np.linalg.det(m)

print "La matriz m es:", m
print "La norma de m es: ", norm
print "El determinante de m es:", det

La matriz es la siguiente: [[ 1  0]
 [ 2 -1]]
La norma de la matriz es:  2.449489742783178
El determinante de la matriz es: -1.0


### Ejercicio 2
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos arrays.

In [11]:
import numpy as np

# Generamos un vector con valores entre 0 y 1 y con paso 0.1. Para ello utilizamos la función arange,
# que funciona de forma análoga a la función range vista en anteriores unidades.
x = np.arange(0., 1.1, 0.1)

# Calculamos el valor del arcocoseno y del arcoseno por cada valor de x utilizando las funciones arcsin y arccos de numpy
arcoseno = np.arcsin(x)
arcocoseno = np.arccos(x)

print "Arcoseno de x para x entre 0 y 1, con paso 0.1:"
print arcoseno
print "Arcocoseno de x para x entre 0 y 1, con paso 0.1:"
print arcocoseno


Arcoseno de x para x entre 0 y 1, con paso 0.1:
[0.         0.10016742 0.20135792 0.30469265 0.41151685 0.52359878
 0.64350111 0.7753975  0.92729522 1.11976951 1.57079633]
Arcocoseno de x para x entre 0 y 1, con paso 0.1:
[1.57079633 1.47062891 1.36943841 1.26610367 1.15927948 1.04719755
 0.92729522 0.79539883 0.64350111 0.45102681 0.        ]


### Ejercicio 4
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [33]:
from random import randint
import numpy as np

# Utilizamos la función randint del módulo random y list comprehensions para generar la lista, como ya vimos en
# unidades anteriores
rand_ints = [randint(0, 9) for _ in range(100)]

# Para calcular la media y desviación estándar utilizamos las funciones mean y std (standard deviation) respectivamente
m = np.mean(rand_ints)
std = np.std(rand_ints)

print "Nuestra lista de valores aleatorios es:", rand_ints
print "Su valor medio es %f, y su desviación estándar es %f" %(m, std)

# Para valores máximo y mínimo, utilizamos max y min
max_val = np.max(rand_ints)
min_val = np.min(rand_ints)

print "Sus valores máximo y mínimo son, respectivamente: %d y %d" %(max_val, min_val)

# Para sumar todos los elementos de la lista, la función sum
sum_values = np.sum(rand_ints)

print "El resultado de la suma de todos los valores de la lista es", sum_values 

# Y finalmente para conseguir una lista de valores únicos, la función unique
unique_values = np.unique(rand_ints)

print "Y la lista de valores únicos es", unique_values


Nuestra lista de valores aleatorios es: [1, 9, 3, 6, 1, 0, 0, 1, 7, 7, 5, 8, 7, 6, 2, 8, 7, 7, 0, 6, 9, 9, 0, 0, 2, 3, 6, 7, 2, 5, 9, 2, 5, 1, 5, 6, 9, 5, 4, 1, 2, 0, 3, 0, 7, 4, 2, 0, 0, 7, 5, 5, 7, 3, 2, 1, 8, 9, 3, 9, 9, 4, 0, 6, 3, 6, 9, 6, 9, 1, 4, 0, 9, 0, 1, 8, 2, 9, 4, 5, 8, 2, 9, 7, 2, 1, 4, 1, 1, 4, 8, 9, 0, 7, 3, 0, 1, 3, 6, 4]
Su valor medio es 4.330000, y su desviación estándar es 3.095335
Sus valores máximo y mínimo son, respectivamente: 9 y 0
El resultado de la suma de todos los valores de la lista es 433
Y la lista de valores únicos es [0 1 2 3 4 5 6 7 8 9]
